/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/chriskery/slurm-bridge-operator/apis/kubecluster.org/v1alpha1"
	scheme "github.com/chriskery/slurm-bridge-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SlurmBridgeJobsGetter has a method to return a SlurmBridgeJobInterface.
// A group's client should implement this interface.
type SlurmBridgeJobsGetter interface {
	SlurmBridgeJobs(namespace string) SlurmBridgeJobInterface
}

// SlurmBridgeJobInterface has methods to work with SlurmBridgeJob resources.
type SlurmBridgeJobInterface interface {
	Create(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.CreateOptions) (*v1alpha1.SlurmBridgeJob, error)
	Update(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.UpdateOptions) (*v1alpha1.SlurmBridgeJob, error)
	UpdateStatus(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.UpdateOptions) (*v1alpha1.SlurmBridgeJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SlurmBridgeJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SlurmBridgeJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SlurmBridgeJob, err error)
	SlurmBridgeJobExpansion
}

// slurmBridgeJobs implements SlurmBridgeJobInterface
type slurmBridgeJobs struct {
	client rest.Interface
	ns     string
}

// newSlurmBridgeJobs returns a SlurmBridgeJobs
func newSlurmBridgeJobs(c *KubeclusterV1alpha1Client, namespace string) *slurmBridgeJobs {
	return &slurmBridgeJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the slurmBridgeJob, and returns the corresponding slurmBridgeJob object, and an error if there is any.
func (c *slurmBridgeJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	result = &v1alpha1.SlurmBridgeJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SlurmBridgeJobs that match those selectors.
func (c *slurmBridgeJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SlurmBridgeJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SlurmBridgeJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested slurmBridgeJobs.
func (c *slurmBridgeJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a slurmBridgeJob and creates it.  Returns the server's representation of the slurmBridgeJob, and an error, if there is any.
func (c *slurmBridgeJobs) Create(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.CreateOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	result = &v1alpha1.SlurmBridgeJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(slurmBridgeJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a slurmBridgeJob and updates it. Returns the server's representation of the slurmBridgeJob, and an error, if there is any.
func (c *slurmBridgeJobs) Update(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.UpdateOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	result = &v1alpha1.SlurmBridgeJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		Name(slurmBridgeJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(slurmBridgeJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *slurmBridgeJobs) UpdateStatus(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.UpdateOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	result = &v1alpha1.SlurmBridgeJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		Name(slurmBridgeJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(slurmBridgeJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the slurmBridgeJob and deletes it. Returns an error if one occurs.
func (c *slurmBridgeJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *slurmBridgeJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched slurmBridgeJob.
func (c *slurmBridgeJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SlurmBridgeJob, err error) {
	result = &v1alpha1.SlurmBridgeJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("slurmbridgejobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
