/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/chriskery/slurm-bridge-operator/apis/kubecluster.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSlurmBridgeJobs implements SlurmBridgeJobInterface
type FakeSlurmBridgeJobs struct {
	Fake *FakeKubeclusterV1alpha1
	ns   string
}

var slurmbridgejobsResource = v1alpha1.SchemeGroupVersion.WithResource("slurmbridgejobs")

var slurmbridgejobsKind = v1alpha1.SchemeGroupVersion.WithKind("SlurmBridgeJob")

// Get takes name of the slurmBridgeJob, and returns the corresponding slurmBridgeJob object, and an error if there is any.
func (c *FakeSlurmBridgeJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(slurmbridgejobsResource, c.ns, name), &v1alpha1.SlurmBridgeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SlurmBridgeJob), err
}

// List takes label and field selectors, and returns the list of SlurmBridgeJobs that match those selectors.
func (c *FakeSlurmBridgeJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SlurmBridgeJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(slurmbridgejobsResource, slurmbridgejobsKind, c.ns, opts), &v1alpha1.SlurmBridgeJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SlurmBridgeJobList{ListMeta: obj.(*v1alpha1.SlurmBridgeJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.SlurmBridgeJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested slurmBridgeJobs.
func (c *FakeSlurmBridgeJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(slurmbridgejobsResource, c.ns, opts))

}

// Create takes the representation of a slurmBridgeJob and creates it.  Returns the server's representation of the slurmBridgeJob, and an error, if there is any.
func (c *FakeSlurmBridgeJobs) Create(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.CreateOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(slurmbridgejobsResource, c.ns, slurmBridgeJob), &v1alpha1.SlurmBridgeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SlurmBridgeJob), err
}

// Update takes the representation of a slurmBridgeJob and updates it. Returns the server's representation of the slurmBridgeJob, and an error, if there is any.
func (c *FakeSlurmBridgeJobs) Update(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.UpdateOptions) (result *v1alpha1.SlurmBridgeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(slurmbridgejobsResource, c.ns, slurmBridgeJob), &v1alpha1.SlurmBridgeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SlurmBridgeJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSlurmBridgeJobs) UpdateStatus(ctx context.Context, slurmBridgeJob *v1alpha1.SlurmBridgeJob, opts v1.UpdateOptions) (*v1alpha1.SlurmBridgeJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(slurmbridgejobsResource, "status", c.ns, slurmBridgeJob), &v1alpha1.SlurmBridgeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SlurmBridgeJob), err
}

// Delete takes name of the slurmBridgeJob and deletes it. Returns an error if one occurs.
func (c *FakeSlurmBridgeJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(slurmbridgejobsResource, c.ns, name, opts), &v1alpha1.SlurmBridgeJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSlurmBridgeJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(slurmbridgejobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SlurmBridgeJobList{})
	return err
}

// Patch applies the patch and returns the patched slurmBridgeJob.
func (c *FakeSlurmBridgeJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SlurmBridgeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(slurmbridgejobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SlurmBridgeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SlurmBridgeJob), err
}
