apiVersion: kubecluster.org/v1alpha1
kind: SlurmBridgeJob
metadata:
  labels:
    app.kubernetes.io/name: slurmbridgejob
    app.kubernetes.io/instance: slurmbridgejob-sample
    app.kubernetes.io/part-of: slurm-bridge-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slurm-bridge-operator
  name: slurmbridgejob-sample
spec:
  partition: debug
  sbatchScript: |
    #!/bin/sh
    #SBATCH --nodes=1
    srun hostname
    hostname
    pwd
    for i in {1..5};do echo $i && sleep 15;done
  runAsUser: 0
  runAsGroup: 0
  ntasks: 3
  workingDir: /tmp
  memPerCpu: 500
  cpusPerTask: 1
  result:
    volume:
      name: myresult
      hostPath:
        path: /tmp/result
        type: DirectoryOrCreate
