apiVersion: kubecluster.org/v1alpha1
kind: SlurmBridgeJob
metadata:
  labels:
    app.kubernetes.io/name: slurmbridgejob
    app.kubernetes.io/instance: slurmbridgejob-sample
    app.kubernetes.io/part-of: slurm-bridge-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slurm-bridge-operator
  name: slurmbridgejob-sample
spec:
  partition: debug
  sbatchScript: |
    #!/bin/sh
    #SBATCH --nodes=1
    #SBATCH --array 1-3
    srun hostname
    hostname
    for i in {1..5};do echo $i && sleep 5;done
#  runAsUser: 1003
#  runAsGroup: 0
  result:
    volume:
      name: myresult
      hostPath:
        path: /tmp/result
        type: DirectoryOrCreate
