apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: configurator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slurm-agent-bridge-operator
    app.kubernetes.io/part-of: slurm-agent-bridge-operator
    app.kubernetes.io/managed-by: kustomize
  name: configurator
  namespace: system
