apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurator
  namespace: system
  labels:
    control-plane: configurator
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: slurm-bridge-operator
    app.kubernetes.io/part-of: slurm-bridge-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: configurator
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /configurator
          args:
            - --endpoint=47.74.15.157:9999
          image: configurator:latest
          name: configurator
          env:
            - name: KUBELET_IMAGE
              value: docker.io/chriskery/slurm-virtual-kubelet:latest
            - name: SERVICE_ACCOUNT
              value: sbo-slurm-virtual-kubelet
            - name: RESULTS_IMAGE
              value: docker.io/chriskery/result-fetcher:latest
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: configurator
      terminationGracePeriodSeconds: 10