name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/chriskery/slurm-agent-bridge-operator

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["1.25.0", "1.26.1", "1.27.1"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/chriskery/slurm-agent-bridge-operator

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ env.GOPATH }}/src/github.com/chriskery/slurm-agent-bridge-operator/go.mod

      - name: Run Go test
        run: |
          make test ENVTEST_K8S_VERSION=${{ matrix.kubernetes-version }}

      - name: Coveralls report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
          working-directory: ${{ env.GOPATH }}/src/github.com/chriskery/slurm-agent-bridge-operator
