# permissions for end users to view slurmbridgejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slurmbridgejob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slurm-bridge-operator
    app.kubernetes.io/part-of: slurm-bridge-operator
    app.kubernetes.io/managed-by: kustomize
  name: slurmbridgejob-viewer-role
rules:
- apiGroups:
  - kubecluster.org.kubecluster.org
  resources:
  - slurmbridgejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubecluster.org.kubecluster.org
  resources:
  - slurmbridgejobs/status
  verbs:
  - get
